### ISSUE TITLE
Wrong label on "select all" checkbox

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/admin-ui#126]
Example: The select all checkbox should either say "Select all 14265 items" or "Select all 143 pages"

![wrongpagen](https://github.com/user-attachments/assets/83853a73-e7e7-4b23-acbd-7cb626d88114)

**Comment by svenvandescheur** [comment]
Fixed in: https://github.com/maykinmedia/admin-ui/pull/159
